name: Go

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test

    - name: Build
      run: |
        cd cmd/sl
        go build -ldflags "-s -w" .
        cd ../..
        cd benchmark
        go build -ldflags "-s -w" .
        cd ..


    - name: Release Continuous
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/main'
      with:
        prerelease: true
        draft: false
        automatic_release_tag: continuous
        title: continuous
        files: |
          cmd/sl/sl
          benchmark/benchmark
        repo_token: ${{ secrets.GITHUB_TOKEN }}
